### ISSUE TITLE
Script launch error python main.py

### ISSUE THREAD

**Issue by jojeju9428** [fabicodes/zigbee2mqtt_ota_updater#2]
Hello,

I am trying to get your srcipt working on my zigbee2mqtt server or on my mqtt mosquitto broker server

I have the following error

pi@zigbee2mqtt:~/zigbee2mqtt_ota_updater $ sudo python main.py
  File "/home/pi/zigbee2mqtt_ota_updater/main.py", line 47
    match msg.topic:
          ^
SyntaxError: invalid syntax

Could you help me make it work?

Thanks

**Comment by fabicodes** [comment]
Sorry, it's a new language feature  ([Structural Pattern Matching](https://peps.python.org/pep-0634/)) introduced in Python 3.10 - so I'd suggest upgrading your python to at least 3.10

**Comment by fabicodes** [comment]
Or just update - I replaced the Pattern Matching with if statements https://github.com/fabicodes/zigbee2mqtt_ota_updater/commit/bc74860dc95d8fc107457b163bc3e2e0cc2994f6

**Comment by jojeju9428** [comment]
It works with the last commit
Python version 3.9.2
Thanks
